---
- hosts: docker-instance
  tasks:
    - name: Build and Tag Docker Image
      shell: |
        docker image build -t $JOB_NAME.$BUILD_ID
        docker image tag $JOB_NAME:$BUILD_ID mitul006/$JOB_NAME:$BUILD_ID
        docker image push mitul006/$JOB_NAME:$BUILD_ID
        docker image tag $JOB_NAME:$BUILD_ID mitul006/$JOB_NAME:latest
        docker image push mitul006/$JOB_NAME:latest
        docker image rmi $JOB_NAME:$BUILD_ID mitul006/$JOB_NAME:$BUILD_ID mitul006/$JOB_NAME:latest
      environment:
        JOB_NAME: "$JOB_NAME"
        BUILD_ID: "$BUILD_ID"
